name: signify
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  camera: ^0.11.0+2
  calendar_view: ^1.2.0
  curved_navigation_bar: ^1.0.6
  
  zego_uikit_signaling_plugin: ^2.8.4
  zego_uikit_prebuilt_call: ^4.15.12
  zego_uikit_prebuilt_live_streaming: ^3.12.8
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  flutter_tts: ^4.0.2
  google_generative_ai: ^0.4.6
  http: ^1.2.2
  http_parser: ^4.0.2
  image: ^4.2.0
  signature: ^5.5.0
  syncfusion_flutter_charts: ^27.1.48
  translator: 
  youtube_player_iframe: ^5.1.5

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: "launcher_icon"

  image_path: "assets/icon.jpeg"

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/ISL_Gifs/
    # - assets/model/
flutter_native_splash:
  color: "#000000"
  image: assets/output-onlinepngtools.png
  android: true
  ios: true
  android_gravity: center
  android_12:
    image: assets/icon.jpeg
    color: "#000000"

    icon_background_color: "#000000"
    image_dark: assets/output-onlinepngtools.png
    icon_background_color_dark: "#000000"
