name: signify
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+2
  curved_navigation_bar: ^1.0.6
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  screenshot: ^3.0.0
  image: ^4.2.0
  youtube_player_iframe: ^5.1.5
  
  signature: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter_launcher_icons:
  android: "launcher_icon"
  
  image_path: "assets/icon.jpeg"

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    # - assets/model/
flutter_native_splash:
  color: "#000000"
  image: assets/output-onlinepngtools.png
  android: true
  ios: true
  android_gravity: center
  android_12:
    image: assets/icon.jpeg
    color: "#000000"

    icon_background_color: "#000000"
    image_dark: assets/output-onlinepngtools.png
    icon_background_color_dark: "#000000"